### PR TITLE
Rewrite and refactor the legacy codebase

### PR DESCRIPTION
**Pull request by tothandras**
Major changes:
- we rewrote the whole client app
- we moved the virtual devices to the server side
- device templates can be easily [configured](https://github.com/RisingStack/concaria/tree/refactoring/config/devices)

TODOs:
- [x] boldchat
- [x] sms link sharing
- [x] custom malfunction events for the air filter
- [x] rules engine
- [x] provision (salesforce integration is still a TODO)
- [x] fan contol buttons indicate the current state
- [x] dynamic channels
- [x] remove filter slider
- [x] display end user name
- [x] make sliders less smooth
- [x] use timeseries' `/latest` endpoint
- [x] remove the `/sensor` channel
- [x] Fan control buttons in the app don't indicate what the current state is (some sort of highlighting/outline or something).
- [x] Dynamic channels are not sending data to the app when I adjust the sliders
- [x] Deplete/Replace buttons for filter don't seem to be doing anything, and the filter box should not have a slider.
- [x] End-user not displaying in app
- [x] Make slider changes "less smooth"
- [x] Dust should be default graph shown
- [x] Remove sensor channel once everything else uses individual channels
- [x] Update names/serials/locations for devices
- [x] Simulator
- [x] Xively-Salesforce information mapping
- [x] Sensor button color/flashing in dynamic way (**wontfix**) (**Adam is good with how it's working/looks - Brian**)
- [x] App crashing when trying to deplete filter
- [x] Salesforce object provisioning (end-users & devices)
- [x] Make entire fan control "pill" clickable in virtual device
- [x] Habanero
- [x] Add log:message as option in rules engine
- [x] Open device appears to be simulating in simulator (**can't reproduce, it looks fine for me - David**)
- [x] Revisit logic of disconnect/connect/error timings and only happening in correct scenarios
- [x] Link to CPM should be based on deployed environment
- [x] Show error in phone app when filter depleted (and other error situations if not done, such as malfunction)
- [x] Phone app errors should persist on the screen until user manually closes (**The notification messages can be set as "sticky", it stays there waiting for the user to close it.**)
- [x] Update Salesforce asset/contact population to use correct fields for deployed environment
(**The new environment variable is `XIVELY_DEVICE_ID_FIELD_NAME` (default: `xively__XI_Device_ID__c`)**)
- [x] Deplete filter "count down" instead of instantly going to 0 (**It just "animates" it, but the value jumps to 0 instantly**)
- [x] For a "dynamic channel" added to a template, if you adjust slider to a value, then refresh page, that value is not maintained in the slider (it is correctly maintained in the phone app) (**because no update value is coming from the virtual device, it doesn't generate values on the dynamic channels - Andras**)
- [x] Boldchat button covering bottom part of graph on phone (from Adam) - This may be non-issue when Boldchat stuff is redone per Andras' conversation with Mark, so we can retest when that's ready (**I don't see this - Andras** https://cloud.githubusercontent.com/assets/4157749/14702384/502ab3ec-07aa-11e6-9261-62ca12cd8c96.pnghttps://cloud.githubusercontent.com/assets/4157749/14702410/84e19e3e-07aa-11e6-8c0b-9f77f73f3a91.png)
- [x] Trigger malfunction button should set sensor values to -255 like the LMI version
- [x] Responsiveness when zooming on Mac (screenshot from Adam) (**there is no overlap anymore**)
- [x] Simulator seems to be running forever instead of stopping after 100 cycles (Adam said it was running when he came back after an hour) (**fixed - David**)
- [x] Fan Speed & Malfunction events no longer showing up in log.  This may be due to the latest deployment of the CPM application, so we should investigate if they changed what they pick up for error log messages. **(Not an issue - Brian)**
- [x] If you run the simulator button, then refresh page, the button shows as "Start Simulator" instead of "Stop Simulator" since simulator is still running
- [x] App should open to demo split screen view, not device list view
- [ ] Fix salesforce tests if the live demo gets stable
- [x] Device malfunction should not disconnect the device.  Because it is disconnected, Salesforce can't communicate with the device to perform the factory reset.
- [x] If I malfunction a device, clear the error in the phone app, and refresh the page, the error shows up again
- [x] All devices except for the demo device show N/A for all sensor and won't update when you manipulate the virtual device.
- [x] Simulator appears to break after running for the first time
- [x] Make rule parser case insensitive
- [x]  Factory reset from Salesforce is not fixing the device

Demo: https://new-concaria.herokuapp.com/

There are a lot of changes, Github can't show them all: https://github.com/RisingStack/concaria/tree/refactoring

Doesn't work anymore (we are targeting `dev`): [Deploy](https://heroku.com/deploy?template=https://github.com/RisingStack/concaria/tree/refactoring-build)

### CODE REVIEW

**Comment by breynolds83** [comment]
Fan control buttons in the app don't indicate what the current state is (some sort of highlighting/outline or something).

**Comment by breynolds83** [comment]
Dynamic channels are not sending data to the app when I adjust the sliders.

**Comment by breynolds83** [comment]
Deplete/Replace buttons for filter don't seem to be doing anything, and the filter box should not have a slider.

**Comment by breynolds83** [comment]
- End-user not displaying in app

**Comment by breynolds83** [comment]
Remove sensor channel once everything else uses individual channels

**Comment by breynolds83** [comment]
- Update names/serials/locations for devices
- Determine end-user name to display
- Heroku "Open App" should launch split screen view of first device, not device list page
- Simulator

**Comment by tothandras** [comment]
Fun fact: `+11811, -27035`

**Pull request merged**
