### PR TITLE
Update landing page

### PR DESCRIPTION
**Pull request by jmeas**
Some of this code was done hastily to meet the deadline. There
may be a few tweaks to make in the future, like removing the use
of tag selectors in the CSS.

Some tidying up that needs to happen:

- [ ] Update link to dashboard. It should be https://app.demo.xively.com/login
- [ ] Use class names rather than tag selectors in CSS
- [ ] Make the grey boxes "expand" a bit on hover, per the design
- [ ] Add proxima nova, then update font sizes to match what's in the PSD
- [ ] Prefetch hover images so that there's no delay when the user hovers
- [ ] DRY up SCSS (use variables for more colors, like the Xively red, for instance)
- [ ] The design makes it out that the "down arrow" in the top section should be clickable. I guess it would just scroll the page down a bit?
- [ ] Add diagonal bg in middle section with grey boxes
- [ ] Remove left margin on the UL containing the grey boxes haha

### CODE REVIEW

**Comment by deathbearbrown** [comment]
+1 the redesign actually made this code better since you got rid of a lot of inline styles. So there's that.

**Comment by deathbearbrown** [comment]
More updates:
- [ ] the "header" (orange) section should be shorter and without all the text, Adam thought it was way too busy/wordy
- [ ] Xively logo in the "header" should be positioned/sized to match that on xively.com
- [ ] we want to remove the "Learn More" text on-hover on each of the 4 boxes
- [ ] we want to make the white area below the boxes a little taller, Adam thought like 120px

**Comment by deathbearbrown** [comment]
screen shot 2016-02-08 at 4 00 41 pm

The one thing I changed from the [landing page screenshot](https://s3.amazonaws.com/uploads.hipchat.com/34833/2477195/sS3PGPPcbzd8iUV/Landing%20Page%20from%20Adam.png)  I was given  was removing the left-padding for the list of the 4 boxes, that way they would lay flush to the side and line up with the logo that has been moved.

**Comment by deathbearbrown** [comment]
Didn't mean to close that.. oops

**Comment by ksiegel** [comment]
I don't see anything that should change that isn't already planned for another sprint story.. so I'm saying it looks good to merge! :+1:

**Pull request merged**
